apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argo-executor:raise-search
  namespace: raise
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: argo-executor
subjects:
- kind: ServiceAccount
  name: raise-search
