version: 0.2

env:
  shell: bash
  secrets-manager:
    SLACK_WEBHOOKURL: "slack:k12stream"

phases:
  install:
    commands:
      - curl -L https://get.helm.sh/helm-v3.15.3-linux-amd64.tar.gz | tar -xvz
      - mv linux-amd64/helm ./helm
      - curl -L -o yq "https://github.com/mikefarah/yq/releases/download/v4.44.2/yq_linux_amd64"
      - chmod +x ./helm ./yq
      - export PATH=$PWD:$PATH
  pre_build:
    commands:
      - aws eks update-kubeconfig --name $K8S_CLUSTER_NAME
      - export SEARCH_IMAGE_NAME=$(cat $CODEBUILD_SRC_DIR_search_build_output/search-image-name.txt)
      - export SEARCH_IMAGE_TAG=$(cat $CODEBUILD_SRC_DIR_search_build_output/search-image-tag.txt)
      - touch ./values.yaml
      - yq e -i '.deploymentDomain="search.raiselearning.org"' ./values.yaml
      - yq e -i '.searchImage.name=strenv(SEARCH_IMAGE_NAME)' ./values.yaml
      - yq e -i '.searchImage.tag=strenv(SEARCH_IMAGE_TAG)' ./values.yaml
      - yq e -i '.opensearchHostEndpoint=strenv(OPENSEARCH_HOST_ENDPOINT)' ./values.yaml
  build:
    commands:
      - helm upgrade -n raise --install -f ./values.yaml raise-search deploy/chart/
      - export SLACK_MESSAGE="raise-search deployment completed successfully for commit $COMMIT_ID"
      - "curl -X POST -H 'Content-type: application/json' --data '{\"text\":\"'\"$SLACK_MESSAGE\"'\"}' $SLACK_WEBHOOKURL"
